/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.AprendendoNoNetBeans;

public class App {
    public int romanToInt(String s) {
            char[] ArrayRoman = s.toCharArray();
            int[] ArrayInt = new int[ArrayRoman.length];
            int conversãoInteiro = 0;
    
            for (int i=0;i<ArrayRoman.length;i++){
                switch (ArrayRoman[i]){
                    case 'M':
                        ArrayInt[i]=1000;
                        break;
                    case 'D':
                        ArrayInt[i]=500;
                        break;
                    case 'C':
                        ArrayInt[i]=100;
                        break;
                    case 'L':
                        ArrayInt[i]=50;
                        break;
                    case 'X':
                        ArrayInt[i]=10;
                        break;
                    case 'V':
                        ArrayInt[i]=5;
                        break;
                    case 'I':
                        ArrayInt[i]=1;
                        break; 
                };
            }
            for (int i=0;i<ArrayInt.length;i++){
                if (i>0 && ArrayInt[i]<ArrayInt[i-1]){
                    conversãoInteiro = ArrayInt[i-1] - ArrayInt[i];
                } else {
                    conversãoInteiro += ArrayInt[i];
                }
            }
            
            
            
            return conversãoInteiro;
        }

    public static void main(String[] args) {
        NewJFrame newJFrame = new NewJFrame();
        newJFrame.setVisible(true);
    }
}
