/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Calculadora;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import javax.swing.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @BeforeEach
    public void setUp() {
        // Inicializa o JTextField antes de cada teste
        App.textField = new JTextField();
        App.textField.setText("");
    }

    @Test
    public void testIncrementarChar() {
        App.incrementarChar('5');
        assertEquals("5", App.textField.getText());

        App.incrementarChar('+');
        assertEquals("5+", App.textField.getText());

        App.incrementarChar('3');
        assertEquals("5+3", App.textField.getText());
    }

    @Test
    public void testLimpar() {
        App.textField.setText("123+45");
        App.limpar();
        assertEquals("", App.textField.getText());
    }

    @Test
    public void testResultadoSomaSimples() {
        App.textField.setText("1+1");
        App.resultado();
        assertEquals("2", App.textField.getText());
    }

    @Test
    public void testResultadoSubtracaoSimples() {
        App.textField.setText("5-2");
        App.resultado();
        assertEquals("3", App.textField.getText());
    }

    @Test
    public void testResultadoMultiplicacaoSimples() {
        App.textField.setText("4*2");
        App.resultado();
        assertEquals("8", App.textField.getText());
    }

    @Test
    public void testResultadoDivisaoSimples() {
        App.textField.setText("8/2");
        App.resultado();
        assertEquals("4", App.textField.getText());
    }

    @Test
    public void testResultadoComplexo() {
        App.textField.setText("3+6*2-4");
        App.resultado();
        assertEquals("11", App.textField.getText());  // Verifica o valor calculado pela lógica atual
    }
}
