/*
 * This source file was generated by the Gradle 'init' task
 */
package treino.java.d;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class App extends JPanel implements ActionListener {

    private int x = 0; // Posição inicial do boneco de palito
    private Timer timer;

    public App() {
        timer = new Timer(30, this); // Configura o timer para atualizar a cada 30 milissegundos
        timer.start();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        // Desenhar um retângulo
        // Desenha o chão
        g2d.setColor(Color.BLACK);
        g2d.drawLine(0, 300, getWidth(), 300);

        // Desenha o boneco de palito
        g2d.setColor(Color.BLUE);
        int baseY = 250; // Base Y do boneco de palito
        g2d.drawLine(x, baseY, x, baseY - 50); // Corpo
        g2d.drawLine(x, baseY - 50, x - 15, baseY - 70); // Braço esquerdo
        g2d.drawLine(x, baseY - 50, x + 15, baseY - 70); // Braço direito
        g2d.drawLine(x, baseY, x - 15, baseY + 30); // Perna esquerda
        g2d.drawLine(x, baseY, x + 15, baseY + 30); // Perna direita
        g2d.drawOval(x - 10, baseY - 70, 20, 20); // Cabeça
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        x += 5; // Move o boneco de palito 5 pixels para a direita
        if (x > getWidth()) {
            x = 0; // Reinicia a posição quando o boneco de palito sair da tela
        }
        repaint(); // Redesenha o painel
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        App app = new App();
        frame.add(app);
        frame.setSize(400, 400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}
