/*
 * This source file was generated by the Gradle 'init' task
 */
package automação.em.java;

import java.awt.Robot;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

public class DesktopAutomation {
    public static void main(String[] args) throws Exception {
        Robot robot = new Robot();

        // Mover o mouse para a posição desejada
        robot.mouseMove(730, 15);

        // Adicionar um pequeno intervalo antes do clique
        Thread.sleep(500);

        // Pressionar o botão do mouse
        robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);

        // Adicionar um pequeno intervalo antes de soltar o botão
        Thread.sleep(100);

        // Soltar o botão do mouse
        robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);

        robot.mouseMove(730, 30);
        Thread.sleep(500);
        robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
        Thread.sleep(100);
        robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);

        robot.keyPress(KeyEvent.VK_G);
        robot.keyRelease(KeyEvent.VK_G);

        robot.keyPress(KeyEvent.VK_I);
        robot.keyRelease(KeyEvent.VK_I);

        robot.keyPress(KeyEvent.VK_T);
        robot.keyRelease(KeyEvent.VK_T);

        robot.keyPress(KeyEvent.VK_H);
        robot.keyRelease(KeyEvent.VK_H);

        robot.keyPress(KeyEvent.VK_U);
        robot.keyRelease(KeyEvent.VK_U);

        robot.keyPress(KeyEvent.VK_B);
        robot.keyRelease(KeyEvent.VK_B);

        robot.keyPress(KeyEvent.VK_ENTER);
        robot.keyRelease(KeyEvent.VK_ENTER);

    }
}
